// <auto-generated />
using System;
using BackendEvently.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evently.Shared.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250624062114_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendEvently.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoryes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "workshop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Foredrag"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Musik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kunst"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Netwærk"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Teknologi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sundhed"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mad & Drikke"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Turnering"
                        });
                });

            modelBuilder.Entity("BackendEvently.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessRequirements = "",
                            CategoryId = 1,
                            Details = "Lær C#",
                            Location = "Room 101",
                            LogoUrl = "",
                            MaxParticipants = 30,
                            Name = "C# Workshop",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessRequirements = "",
                            CategoryId = 2,
                            Details = "Sommerfest for alle",
                            Location = "Café",
                            LogoUrl = "",
                            MaxParticipants = 100,
                            Name = "Sommerfest",
                            Price = 50m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessRequirements = "",
                            CategoryId = 7,
                            Details = "Bliv klogere på AI",
                            Location = "Auditorium",
                            LogoUrl = "",
                            MaxParticipants = 80,
                            Name = "Foredrag om AI",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccessRequirements = "",
                            CategoryId = 8,
                            Details = "Morgenyoga",
                            Location = "Byparken",
                            LogoUrl = "",
                            MaxParticipants = 20,
                            Name = "Yoga i parken",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccessRequirements = "",
                            CategoryId = 6,
                            Details = "Mød nye mennesker",
                            Location = "Lounge",
                            LogoUrl = "",
                            MaxParticipants = 40,
                            Name = "Netværksaften",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccessRequirements = "",
                            CategoryId = 9,
                            Details = "Lær at lave mad",
                            Location = "Køkkenet",
                            LogoUrl = "",
                            MaxParticipants = 15,
                            Name = "Madlavningskursus",
                            Price = 100m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            AccessRequirements = "",
                            CategoryId = 5,
                            Details = "Se moderne kunst",
                            Location = "Galleri",
                            LogoUrl = "",
                            MaxParticipants = 60,
                            Name = "Kunstudstilling",
                            Price = 25m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            AccessRequirements = "",
                            CategoryId = 3,
                            Details = "Turnering for alle",
                            Location = "Stadion",
                            LogoUrl = "",
                            MaxParticipants = 22,
                            Name = "Fodboldturnering",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            AccessRequirements = "",
                            CategoryId = 4,
                            Details = "Live musik",
                            Location = "Pladsen",
                            LogoUrl = "",
                            MaxParticipants = 200,
                            Name = "Musikfestival",
                            Price = 150m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            AccessRequirements = "",
                            CategoryId = 10,
                            Details = "Diverse aktiviteter",
                            Location = "Fælleshuset",
                            LogoUrl = "",
                            MaxParticipants = 50,
                            Name = "Andet Event",
                            Price = 0m,
                            StartTime = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BackendEvently.Model.EventPartipaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteretAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("BackendEvently.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emailaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emailaddress = "admin@evently.com",
                            PasswordHash = "admin1234",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Emailaddress = "alice@example.com",
                            PasswordHash = "password1234",
                            Role = "user",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 3,
                            Emailaddress = "bob@example.com",
                            PasswordHash = "password1234",
                            Role = "user",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 4,
                            Emailaddress = "carol@example.com",
                            PasswordHash = "password1234",
                            Role = "user",
                            Username = "carol"
                        },
                        new
                        {
                            Id = 5,
                            Emailaddress = "dave@example.com",
                            PasswordHash = "password1234",
                            Role = "user",
                            Username = "dave"
                        },
                        new
                        {
                            Id = 6,
                            Emailaddress = "eve@example.com",
                            PasswordHash = "password1234",
                            Role = "user",
                            Username = "eve"
                        });
                });

            modelBuilder.Entity("BackendEvently.Model.Event", b =>
                {
                    b.HasOne("BackendEvently.Model.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendEvently.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendEvently.Model.EventPartipaint", b =>
                {
                    b.HasOne("BackendEvently.Model.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendEvently.Model.User", "User")
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendEvently.Model.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BackendEvently.Model.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BackendEvently.Model.User", b =>
                {
                    b.Navigation("EventParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
